using System;
using UnityEngine;

namespace Postica.BindingSystem
{
    /// <summary>
    /// Marks that the object definition has been auto generated
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Method)]
    public class AutoGeneratedAttribute : PropertyAttribute
    {
        /// <summary>
        /// The type of the generator
        /// </summary>
        public Type Generator { get; private set; }

        /// <summary>
        /// Mark this object as auto generated.
        /// </summary>
        /// <param name="generator">The type of the generator</param>
        public AutoGeneratedAttribute(Type generator)
        {
            this.Generator = generator;
        }
    }
}
